name: Project tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.4.0
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: '1.12.0.1530'
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run Clojure tests
        run: clojure -X:test-clj
      - name: Run ClojureScript tests
        run: clojure -M:test-cljs
