name: Project tests
on: [push]
jobs:
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1155'
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-datascript-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-datascript-
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
      - name: Run Clojure tests
        run: clojure -X:test-clj
      - name: Run ClojureScript tests
        run: clojure -M:test-cljs
